export const DATE_FORMAT = 'DD/MM/YYYY'
export const MONTH_YEAR_FORMAT = 'MMM YYYY'
export const YEAR_FORMAT = 'YYYY'
export const DATE_TIME_FORMAT = 'DD/MM/YY HH:mm'
export const REVERSE_DATE_TIME_FORMAT = 'HH:mm DD/MM/YY'
